baseURL = "/"
languageCode = "en-au"
title = "Codes of Wholess"
theme = "kube"
description = ""
Paginate = 10
[Params]
  RSSLink = "/index.xml"
  author = "Claudia Carmen Anton"
  github = "ClaudiaCarmenAnton"
  twitter = "ClaudiaCAnton"

[[menu.main]]
  name = "Blog"
  weight = -100
  url = "/blog/"
[[menu.main]]
  name = "Contact"
  weight = -100
  url = "/contact/"
[[menu.main]]
  name = "Recipes"
  weight = -100
  url ="/recipes/"
[[menu.main]]
  name = "Why Claudia"
  weight = -100
  url ="/why-claudia/"

[taxonomies]
  recipes = "recipes"
