baseURL = "/"
languageCode = "en-au"
title = "Taylored Technology"
theme = "kube"
description = "Uniting Humanity with the Gift of Technology"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Taylored Technology" # add your company name
  github = "TayloredTechnology" # add your github profile name
  twitter = "" # add your twitter profile

[[menu.main]]
    name = "Services"
    weight = -100
    url = "/services/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Engagements"
    weight = -100
    url = "/engagements/"
[[menu.main]]
    name = "Contact"
    weight = -100
    url = "/contact/"
